In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\bhatn\Desktop\data science upflairs\Data-Science-AI-and-ML\Pandas\Credit (1).csv")

In [4]:
df.dropna(inplace=True)

In [5]:
df

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4501 rows x 9 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4501 entries, 0 to 4520
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        4501 non-null   float64
 1   job        4501 non-null   object 
 2   marital    4501 non-null   object 
 3   education  4501 non-null   object 
 4   balance    4501 non-null   int64  
 5   housing    4501 non-null   object 
 6   duration   4501 non-null   float64
 7   campaign   4501 non-null   int64  
 8   approval   4501 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 351.6+ KB


In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4516    False
4517    False
4518    False
4519    False
4520    False
Length: 4501, dtype: bool

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.describe()

age       balance      duration     campaign
count  4500.000000   4500.000000  4.500000e+03  4500.000000
mean     41.391111   1423.561111  6.007646e+03     2.792667
std      13.983651   3014.058886  3.578213e+05     3.108241
min     -38.000000  -3313.000000 -7.990000e+02     1.000000
25%      33.000000     68.750000  1.040000e+02     1.000000
50%      39.000000    444.500000  1.850000e+02     2.000000
75%      49.000000   1480.000000  3.290000e+02     3.000000
max     416.000000  71188.000000  2.395650e+07    50.000000

In [11]:
df

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4500 rows x 9 columns]

In [12]:
df.head(10)

age            job  marital  education  balance housing  duration  \
0  30.0     unemployed  married    primary     1787      no      79.0   
1  33.0       services  married  secondary     4789     yes     220.0   
2  35.0     management   single   tertiary     1350     yes     185.0   
3  30.0     management  married   tertiary     1476     yes     199.0   
4  59.0    blue-collar  married  secondary        0     yes     226.0   
5  35.0     management   single   tertiary      747      no     141.0   
6  36.0  self-employed  married   tertiary      307     yes     341.0   
7  39.0     technician  married  secondary      147     yes     151.0   
8  41.0   entrepreneur  married   tertiary      221     yes      57.0   
9  43.0       services  married    primary      -88     yes     313.0   

   campaign approval  
0         1       no  
1         1       no  
2         1       no  
3         4       no  
4         1       no  
5         2       no  
6         1       no  
7         2       no  
8         2       no  
9         1       no

In [13]:
df.tail(10)

age            job  marital  education  balance housing  duration  \
4511  46.0    blue-collar  married  secondary      668     yes    1263.0   
4512  40.0    blue-collar  married  secondary     1100     yes     660.0   
4513  49.0    blue-collar  married  secondary      322      no     356.0   
4514  38.0    blue-collar  married  secondary     1205     yes      45.0   
4515  32.0       services   single  secondary      473     yes     624.0   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
4511         2      yes  
4512         2       no  
4513         2       no  
4514         4       no  
4515         5       no  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no

In [14]:
# df['job status']

In [15]:
df['job'].value_counts()

job
management       958
blue-collar      943
technician       765
admin.           477
services         415
retired          230
self-employed    182
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

In [16]:
df['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

In [17]:
df['job'].nunique()

12

In [18]:
df[df['job'] == 'blue-collar']

age          job  marital  education  balance housing  duration  \
4     59.0  blue-collar  married  secondary        0     yes     226.0   
14    31.0  blue-collar  married  secondary      360     yes      89.0   
26    55.0  blue-collar  married    primary      627     yes     247.0   
37    32.0  blue-collar  married  secondary     2089     yes     132.0   
42    52.0  blue-collar  married  secondary     1117     yes     365.0   
...    ...          ...      ...        ...      ...     ...       ...   
4511  46.0  blue-collar  married  secondary      668     yes    1263.0   
4512  40.0  blue-collar  married  secondary     1100     yes     660.0   
4513  49.0  blue-collar  married  secondary      322      no     356.0   
4514  38.0  blue-collar  married  secondary     1205     yes      45.0   
4519  28.0  blue-collar  married  secondary     1137      no     129.0   

      campaign approval  
4            1       no  
14           1       no  
26           1       no  
37           1      yes  
42           1       no  
...        ...      ...  
4511         2      yes  
4512         2       no  
4513         2       no  
4514         4       no  
4519         4       no  

[943 rows x 9 columns]

In [19]:
df.rename(columns={'job' : 'job status'}, inplace=True)

In [20]:
df

age     job status  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4500 rows x 9 columns]

In [21]:
df.drop(['campaign'] ,axis=1 ,inplace=True)

In [22]:
df

age     job status  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

     approval  
0          no  
1          no  
2          no  
3          no  
4          no  
...       ...  
4516       no  
4517       no  
4518       no  
4519       no  
4520       no  

[4500 rows x 8 columns]

In [23]:
char = df.select_dtypes(include='object')

In [24]:
char 

job status  marital  education housing approval
0        unemployed  married    primary      no       no
1          services  married  secondary     yes       no
2        management   single   tertiary     yes       no
3        management  married   tertiary     yes       no
4       blue-collar  married  secondary     yes       no
...             ...      ...        ...     ...      ...
4516       services  married  secondary     yes       no
4517  self-employed  married   tertiary     yes       no
4518     technician  married  secondary      no       no
4519    blue-collar  married  secondary      no       no
4520   entrepreneur   single   tertiary     yes       no

[4500 rows x 5 columns]

In [25]:
num = df.select_dtypes(exclude='object')

In [26]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [27]:
char['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [28]:
job_status_dic={
    'married':0,
    'single' :1,
    'divorced' :2
    }

In [29]:
char['marital'] = char['marital'].map(job_status_dic)

In [30]:
char['marital'].unique()

array([0, 1, 2])

In [31]:
char['education'].unique()

array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)

In [32]:
education_dict ={
    'primary' : 0,
    'secondary' :1,
    'tertiary': 2,
    'unknown':3
}

In [33]:
char['education'] = char['education'].map(education_dict)

In [34]:
char['education'].unique()

array([0, 1, 2, 3])

In [35]:
char

job status  marital  education housing approval
0        unemployed        0          0      no       no
1          services        0          1     yes       no
2        management        1          2     yes       no
3        management        0          2     yes       no
4       blue-collar        0          1     yes       no
...             ...      ...        ...     ...      ...
4516       services        0          1     yes       no
4517  self-employed        0          2     yes       no
4518     technician        0          1      no       no
4519    blue-collar        0          1      no       no
4520   entrepreneur        1          2     yes       no

[4500 rows x 5 columns]

In [67]:
from sklearn.preprocessing import LabelEncoder   ## label encoder is use for whn classes are more then how to assign it ...  ##onedotcoder == for assign 01=,1
Le =LabelEncoder()
char['job status']=Le.fit_transform(char['job status'])
char['housing']=Le.fit_transform(char['housing'])


In [68]:
char['job status'].unique()

array([10,  7,  4,  1,  6,  9,  2,  0,  8,  3,  5, 11])

In [69]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [70]:
char

job status  marital  education  housing approval
0             10        0          0        0       no
1              7        0          1        1       no
2              4        1          2        1       no
3              4        0          2        1       no
4              1        0          1        1       no
...          ...      ...        ...      ...      ...
4516           7        0          1        1       no
4517           6        0          2        1       no
4518           9        0          1        0       no
4519           1        0          1        0       no
4520           2        1          2        1       no

[4500 rows x 5 columns]

In [71]:
clean_data = pd.concat([char,num], axis=1)

In [72]:
app_dict ={'no':0, 'yes':1}

In [73]:
clean_data['approval']= clean_data['approval'].map(app_dict)

In [74]:
clean_data

job status  marital  education  housing  approval   age  balance  \
0             10        0          0        0         0  30.0     1787   
1              7        0          1        1         0  33.0     4789   
2              4        1          2        1         0  35.0     1350   
3              4        0          2        1         0  30.0     1476   
4              1        0          1        1         0  59.0        0   
...          ...      ...        ...      ...       ...   ...      ...   
4516           7        0          1        1         0  99.0     -333   
4517           6        0          2        1         0  57.0    -3313   
4518           9        0          1        0         0  57.0      295   
4519           1        0          1        0         0  28.0     1137   
4520           2        1          2        1         0  44.0     1136   

      duration  
0         79.0  
1        220.0  
2        185.0  
3        199.0  
4        226.0  
...        ...  
4516     329.0  
4517    -153.0  
4518     151.0  
4519     129.0  
4520     345.0  

[4500 rows x 8 columns]

In [75]:
clean_data.to_csv('new_cleaned_credit.csv')

In [76]:
# df.dropna(inplace=True)

In [112]:
clean_data

job status  marital  education  housing  approval   age  balance  \
0             10        0          0        0         0  30.0     1787   
1              7        0          1        1         0  33.0     4789   
2              4        1          2        1         0  35.0     1350   
3              4        0          2        1         0  30.0     1476   
4              1        0          1        1         0  59.0        0   
...          ...      ...        ...      ...       ...   ...      ...   
4516           7        0          1        1         0  99.0     -333   
4517           6        0          2        1         0  57.0    -3313   
4518           9        0          1        0         0  57.0      295   
4519           1        0          1        0         0  28.0     1137   
4520           2        1          2        1         0  44.0     1136   

      duration  
0         79.0  
1        220.0  
2        185.0  
3        199.0  
4        226.0  
...        ...  
4516     329.0  
4517    -153.0  
4518     151.0  
4519     129.0  
4520     345.0  

[4500 rows x 8 columns]

In [78]:
# df1 = pd.read_csv('new_cleaned_Credit.csv')

In [79]:
# df1

In [80]:
# df1.dropna(inplace=True)

In [81]:
# x =df1.drop('U', axis =1) 

In [82]:
# y =df1[['age']]

In [83]:
# df1.drop('Unnamed: 0', axis =1,inplace=True) 


In [84]:
x = clean_data.drop('approval' , axis =1)

In [85]:
y = clean_data[['approval']]

In [86]:
x

job status  marital  education  housing   age  balance  duration
0             10        0          0        0  30.0     1787      79.0
1              7        0          1        1  33.0     4789     220.0
2              4        1          2        1  35.0     1350     185.0
3              4        0          2        1  30.0     1476     199.0
4              1        0          1        1  59.0        0     226.0
...          ...      ...        ...      ...   ...      ...       ...
4516           7        0          1        1  99.0     -333     329.0
4517           6        0          2        1  57.0    -3313    -153.0
4518           9        0          1        0  57.0      295     151.0
4519           1        0          1        0  28.0     1137     129.0
4520           2        1          2        1  44.0     1136     345.0

[4500 rows x 7 columns]

In [87]:
y

approval
0            0
1            0
2            0
3            0
4            0
...        ...
4516         0
4517         0
4518         0
4519         0
4520         0

[4500 rows x 1 columns]

In [88]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [89]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape  

((3600, 7), (900, 7), (3600, 1), (900, 1))

In [90]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

In [91]:
# y_train['approval'].nunique()

In [92]:
# app_dict = {'no':0, 'yes':1}

In [93]:
# y_train['approval']= y_train['approval'].map(app_dict)

In [94]:
# y_train['approval'].unique()

In [95]:
# x_train['housing']= x_train['housing'].map(app_dict)

In [96]:
# char  

In [97]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [98]:
# from sklearn.linear_model import LinearRegression

# Lr = LinearRegression()
# Lr.fit(x_train , y_train)

In [99]:
dt.score(x_train, y_train) 

1.0

In [100]:
# x_test['housing']= x_train['housing'].map(app_dict)

In [101]:
pred =dt.predict(x_test)

In [102]:
pred =pd.DataFrame(pred)


In [103]:
y_test

approval
2332         1
3702         0
2988         1
3006         1
473          1
...        ...
916          0
814          0
2953         1
3726         0
3272         0

[900 rows x 1 columns]

In [104]:
x_test

job status  marital  education  housing    age  balance  duration
2332           4        0          2        1   30.0      102     470.0
3702           1        0          1        1   48.0     1738     349.0
2988           2        1          1        0  338.0     2543     223.0
3006           6        0          3        0   51.0     2094     458.0
473            0        0          1        0   61.0     4608     212.0
...          ...      ...        ...      ...    ...      ...       ...
916            1        0          1        0   36.0       13     284.0
814            9        0          1        1   47.0      -75      57.0
2953           8        1          2        0   22.0      691     338.0
3726           9        0          3        1   45.0      473     147.0
3272           7        1          1        1   44.0     5045      20.0

[900 rows x 7 columns]

In [105]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train , y_train)

c:\Users\bhatn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [106]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [107]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [108]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train , y_train)

c:\Users\bhatn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [114]:
knn.score(x_test , y_test)  

0.88

In [109]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [110]:
knn.predict(x_test)

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [111]:
from sklearn.ensemble import RandomForestClassifier

Rfc = RandomForestClassifier()
Rfc.fit(x_train , y_train)

c:\Users\bhatn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [113]:
from sklearn.metrics import classification_report,precision_score,recall_score,confusion_matrix,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [115]:
df = DecisionTreeClassifier()
df.fit(x_train,y_train)

DecisionTreeClassifier()

In [116]:
df.score(x_test,y_test)

0.8311111111111111

In [117]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.92      0.89      0.90       799
           1       0.29      0.37      0.32       101

    accuracy                           0.83       900
   macro avg       0.60      0.63      0.61       900
weighted avg       0.85      0.83      0.84       900



In [118]:
print(precision_score(y_test,pred))
print(recall_score(y_test,pred))
print(f1_score(y_test,pred))

0.2890625
0.36633663366336633
0.3231441048034934


In [119]:
print(confusion_matrix(y_test,pred))

[[708  91]
 [ 64  37]]
