In [1]:
import pandas as pd


In [2]:
df = pd.read_csv(r'C:\Users\bhatn\Desktop\data science upflairs\Data-Science-AI-and-ML\Projects\Insurance\insurance dataset.csv')

In [3]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [5]:
df.duplicated().sum()

np.int64(1)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.describe()

age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [8]:
char = df.select_dtypes(include='object')

In [9]:
char

sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

In [10]:
num = df.select_dtypes(exclude=['object'])

In [11]:
num

age     bmi  children      charges
0      19  27.900         0  16884.92400
1      18  33.770         1   1725.55230
2      28  33.000         3   4449.46200
3      33  22.705         0  21984.47061
4      32  28.880         0   3866.85520
...   ...     ...       ...          ...
1333   50  30.970         3  10600.54830
1334   18  31.920         0   2205.98080
1335   18  36.850         0   1629.83350
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[1337 rows x 4 columns]

In [12]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder  
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])



In [14]:
df['sex'].unique()

array([0, 1])

In [15]:
df['smoker'].unique()

array([1, 0])

In [16]:
df['region'].unique()

array([3, 2, 1, 0])

In [17]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1337 rows x 7 columns]

In [18]:
x = df.drop('charges', axis=1)
y = df['charges']

In [19]:
x

age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
1333   50    1  30.970         3       0       1
1334   18    0  31.920         0       0       0
1335   18    0  36.850         0       0       2
1336   21    0  25.800         0       0       3
1337   61    0  29.070         0       1       1

[1337 rows x 6 columns]

In [20]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1069, 6), (268, 6), (1069,), (268,))

In [26]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor() 
model.fit(x_train, y_train)

DecisionTreeRegressor()

In [27]:
model.score(x_test, y_test)

0.7748470099041644

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()  
model.fit(x_train, y_train)

LinearRegression()

In [29]:
model.score(x_test, y_test)

0.8068466322629111

In [30]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [31]:
from sklearn.svm import SVR
model = SVR()
model.fit(x_train, y_train)

SVR()

In [32]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()   
model.fit(x_train, y_train)

KNeighborsRegressor()

In [33]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor() 
model.fit(x_train, y_train) 

RandomForestRegressor()

In [34]:
from sklearn.metrics import classification_report,precision_score,recall_score,confusion_matrix,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [35]:
df = DecisionTreeRegressor()
df.fit(x_train,y_train)

DecisionTreeRegressor()

In [36]:
df.score(x_test, y_test)

0.7826485852991425

In [37]:
pred = df.predict(x_test)

In [38]:
pred

array([ 9361.3268 ,  4529.477  , 10848.1343 , 44585.45587, 18963.17192,
        8978.1851 , 36219.40545,  2007.945  ,  7727.2532 , 10407.08585,
       13616.3586 , 23065.4207 , 58571.07448, 12982.8747 ,  5989.52365,
        8520.026  ,  4830.63   , 39871.7043 ,  3847.674  ,  3561.8889 ,
        1748.774  , 22331.5668 ,  8978.1851 , 19719.6947 , 37079.372  ,
       26018.95052, 42560.4304 , 47928.03   ,  8930.93455, 28468.91901,
        4134.08245,  9630.397  ,  1720.3537 , 12928.7911 , 48549.17835,
        9877.6077 ,  2913.569  ,  4906.40965, 22412.6485 ,  8240.5896 ,
        2217.46915, 21880.82   , 41034.2214 ,  9174.13565,  8515.7587 ,
        3353.284  ,  2217.46915,  7633.7206 ,  3956.07145,  7512.267  ,
        4058.1161 ,  7050.0213 , 19964.7463 ,  1880.487  ,  7371.772  ,
        8116.26885,  9617.66245, 12609.88702, 43943.8761 ,  9222.4026 ,
       11299.343  ,  5246.047  , 29186.48236,  1708.0014 , 11538.421  ,
       13047.33235,  6067.12675, 21774.32215, 16884.924  , 14418

In [39]:
print(classification_report(y_test,pred))

ValueError: continuous is not supported

In [40]:
print(precision_score(y_test,pred))
print(recall_score(y_test,pred))
print(f1_score(y_test,pred))

ValueError: continuous is not supported