In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\bhatn\Desktop\data science upflairs\Data-Science-AI-and-ML\Pandas\laptopPrice.csv')

In [3]:
df

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4   
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3      ASUS           Intel        Core i5            10th   8 GB     DDR4   
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   
..      ...             ...            ...             ...    ...      ...   
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
822  Lenovo             AMD        Ryzen 5            10th   8 GB     DDR4   

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual   
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual   
..       ...      ...      ...     ...             ...         ...   
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   Price   rating  Number of Ratings  \
0    No warranty          No       No   34649  2 stars                  3   
1    No warranty          No       No   38999  3 stars                 65   
2    No warranty          No       No   39999  3 stars                  8   
3    No warranty          No       No   69990  3 stars                  0   
4    No warranty          No       No   26990  3 stars                  0   
..           ...         ...      ...     ...      ...                ...   
818       1 year          No       No  135990  3 stars                  0   
819       1 year          No       No  144990  3 stars                  0   
820       1 year          No       No  149990  3 stars                  0   
821       1 year          No       No  142990  3 stars                  0   
822  No warranty          No       No   57490  4 stars                 18   

     Number of Reviews  
0                    0  
1                    5  
2                    1  
3                    0  
4                    0  
..                 ...  
818                  0  
819                  0  
820                  0  
821                  0  
822                  4  

[823 rows x 19 columns]

In [4]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
818    False
819    False
820    False
821    False
822    False
Length: 823, dtype: bool

In [5]:
df.duplicated().sum()

np.int64(21)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [8]:
df.dropna(inplace=True)

In [9]:
df

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4   
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3      ASUS           Intel        Core i5            10th   8 GB     DDR4   
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   
..      ...             ...            ...             ...    ...      ...   
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
822  Lenovo             AMD        Ryzen 5            10th   8 GB     DDR4   

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual   
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual   
..       ...      ...      ...     ...             ...         ...   
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   Price   rating  Number of Ratings  \
0    No warranty          No       No   34649  2 stars                  3   
1    No warranty          No       No   38999  3 stars                 65   
2    No warranty          No       No   39999  3 stars                  8   
3    No warranty          No       No   69990  3 stars                  0   
4    No warranty          No       No   26990  3 stars                  0   
..           ...         ...      ...     ...      ...                ...   
818       1 year          No       No  135990  3 stars                  0   
819       1 year          No       No  144990  3 stars                  0   
820       1 year          No       No  149990  3 stars                  0   
821       1 year          No       No  142990  3 stars                  0   
822  No warranty          No       No   57490  4 stars                 18   

     Number of Reviews  
0                    0  
1                    5  
2                    1  
3                    0  
4                    0  
..                 ...  
818                  0  
819                  0  
820                  0  
821                  0  
822                  4  

[802 rows x 19 columns]

In [10]:
char = df.select_dtypes(include='object')

In [11]:
char

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4   
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3      ASUS           Intel        Core i5            10th   8 GB     DDR4   
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   
..      ...             ...            ...             ...    ...      ...   
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
822  Lenovo             AMD        Ryzen 5            10th   8 GB     DDR4   

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual   
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual   
..       ...      ...      ...     ...             ...         ...   
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   rating  
0    No warranty          No       No  2 stars  
1    No warranty          No       No  3 stars  
2    No warranty          No       No  3 stars  
3    No warranty          No       No  3 stars  
4    No warranty          No       No  3 stars  
..           ...         ...      ...      ...  
818       1 year          No       No  3 stars  
819       1 year          No       No  3 stars  
820       1 year          No       No  3 stars  
821       1 year          No       No  3 stars  
822  No warranty          No       No  4 stars  

[802 rows x 16 columns]

In [12]:
num = df.select_dtypes(exclude='object')

In [13]:
num

Price  Number of Ratings  Number of Reviews
0     34649                  3                  0
1     38999                 65                  5
2     39999                  8                  1
3     69990                  0                  0
4     26990                  0                  0
..      ...                ...                ...
818  135990                  0                  0
819  144990                  0                  0
820  149990                  0                  0
821  142990                  0                  0
822   57490                 18                  4

[802 rows x 3 columns]

In [14]:
df['brand'].nunique()

8

In [15]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['brand'] = le.fit_transform(char['brand'])

In [17]:
char['brand'].unique()

array([1, 5, 7, 2, 4, 3, 6, 0])

In [18]:
char

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0        1           Intel        Core i3            10th   4 GB     DDR4   
1        5           Intel        Core i3            10th   4 GB     DDR4   
2        5           Intel        Core i3            10th   4 GB     DDR4   
3        1           Intel        Core i5            10th   8 GB     DDR4   
4        1           Intel   Celeron Dual   Not Available   4 GB     DDR4   
..     ...             ...            ...             ...    ...      ...   
818      1             AMD        Ryzen 9   Not Available   4 GB     DDR4   
819      1             AMD        Ryzen 9   Not Available   4 GB     DDR4   
820      1             AMD        Ryzen 9   Not Available   4 GB     DDR4   
821      1             AMD        Ryzen 9   Not Available   4 GB     DDR4   
822      5             AMD        Ryzen 5            10th   8 GB     DDR4   

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual   
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual   
..       ...      ...      ...     ...             ...         ...   
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   rating  
0    No warranty          No       No  2 stars  
1    No warranty          No       No  3 stars  
2    No warranty          No       No  3 stars  
3    No warranty          No       No  3 stars  
4    No warranty          No       No  3 stars  
..           ...         ...      ...      ...  
818       1 year          No       No  3 stars  
819       1 year          No       No  3 stars  
820       1 year          No       No  3 stars  
821       1 year          No       No  3 stars  
822  No warranty          No       No  4 stars  

[802 rows x 16 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['processor_brand'] = le.fit_transform(char['processor_brand'])

In [20]:
char['processor_brand'].unique()

array([1, 0, 2])

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['processor_name'] = le.fit_transform(char['processor_name'])

In [22]:
char['processor_name'].unique()

array([ 1,  2,  0,  8,  3,  4,  5,  6,  7,  9, 10])

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['processor_gnrtn']= le.fit_transform(char['processor_gnrtn'])

In [24]:
char['processor_gnrtn'].unique()

array([0, 7, 1, 4, 5, 6, 3, 2])

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['ram_gb']= le.fit_transform(char['ram_gb'])

In [26]:
char['ram_gb'].unique()

array([2, 3, 0, 1])

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['ram_type'] = le.fit_transform(char['ram_type'])

In [28]:
char['ram_type'].unique()

array([1, 4, 5, 2, 0, 3])

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['ssd'] = le.fit_transform(char['ssd'])

In [30]:
char['ssd'].unique()


array([0, 6, 4, 2, 1, 3, 5])

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['hdd']= le.fit_transform(char['hdd'])

In [32]:
char['hdd'].unique()


array([1, 0, 3, 2])

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
char['os']= le.fit_transform(char['os'])
char['os_bit']= le.fit_transform(char['os_bit'])
char['graphic_card_gb']= le.fit_transform(char['graphic_card_gb'])
char['weight']= le.fit_transform(char['weight'])
char['warranty']= le.fit_transform(char['warranty'])
char['Touchscreen']= le.fit_transform(char['Touchscreen'])
char['msoffice']= le.fit_transform(char['msoffice'])
char['rating']= le.fit_transform(char['rating'])



In [34]:
char

brand  processor_brand  processor_name  processor_gnrtn  ram_gb  \
0        1                1               1                0       2   
1        5                1               1                0       2   
2        5                1               1                0       2   
3        1                1               2                0       3   
4        1                1               0                7       2   
..     ...              ...             ...              ...     ...   
818      1                0              10                7       2   
819      1                0              10                7       2   
820      1                0              10                7       2   
821      1                0              10                7       2   
822      5                0               8                0       3   

     ram_type  ssd  hdd  os  os_bit  graphic_card_gb  weight  warranty  \
0           1    0    1   2       1                0       0         3   
1           1    0    1   2       1                0       0         3   
2           1    0    1   2       1                0       0         3   
3           1    6    0   2       0                1       0         3   
4           1    0    3   2       1                0       0         3   
..        ...  ...  ...  ..     ...              ...     ...       ...   
818         1    1    0   2       1                0       0         0   
819         1    1    0   2       1                0       0         0   
820         1    1    0   2       1                2       0         0   
821         1    1    0   2       1                2       0         0   
822         1    6    0   0       1                0       2         3   

     Touchscreen  msoffice  rating  
0              0         0       1  
1              0         0       2  
2              0         0       2  
3              0         0       2  
4              0         0       2  
..           ...       ...     ...  
818            0         0       2  
819            0         0       2  
820            0         0       2  
821            0         0       2  
822            0         0       3  

[802 rows x 16 columns]

In [35]:
num

Price  Number of Ratings  Number of Reviews
0     34649                  3                  0
1     38999                 65                  5
2     39999                  8                  1
3     69990                  0                  0
4     26990                  0                  0
..      ...                ...                ...
818  135990                  0                  0
819  144990                  0                  0
820  149990                  0                  0
821  142990                  0                  0
822   57490                 18                  4

[802 rows x 3 columns]

In [36]:
clean_data = pd.concat([char,num],axis=1)

In [37]:
clean_data

brand  processor_brand  processor_name  processor_gnrtn  ram_gb  \
0        1                1               1                0       2   
1        5                1               1                0       2   
2        5                1               1                0       2   
3        1                1               2                0       3   
4        1                1               0                7       2   
..     ...              ...             ...              ...     ...   
818      1                0              10                7       2   
819      1                0              10                7       2   
820      1                0              10                7       2   
821      1                0              10                7       2   
822      5                0               8                0       3   

     ram_type  ssd  hdd  os  os_bit  graphic_card_gb  weight  warranty  \
0           1    0    1   2       1                0       0         3   
1           1    0    1   2       1                0       0         3   
2           1    0    1   2       1                0       0         3   
3           1    6    0   2       0                1       0         3   
4           1    0    3   2       1                0       0         3   
..        ...  ...  ...  ..     ...              ...     ...       ...   
818         1    1    0   2       1                0       0         0   
819         1    1    0   2       1                0       0         0   
820         1    1    0   2       1                2       0         0   
821         1    1    0   2       1                2       0         0   
822         1    6    0   0       1                0       2         3   

     Touchscreen  msoffice  rating   Price  Number of Ratings  \
0              0         0       1   34649                  3   
1              0         0       2   38999                 65   
2              0         0       2   39999                  8   
3              0         0       2   69990                  0   
4              0         0       2   26990                  0   
..           ...       ...     ...     ...                ...   
818            0         0       2  135990                  0   
819            0         0       2  144990                  0   
820            0         0       2  149990                  0   
821            0         0       2  142990                  0   
822            0         0       3   57490                 18   

     Number of Reviews  
0                    0  
1                    5  
2                    1  
3                    0  
4                    0  
..                 ...  
818                  0  
819                  0  
820                  0  
821                  0  
822                  4  

[802 rows x 19 columns]

In [38]:
clean_data.to_csv('cleaned_laptop.csv')

In [39]:
x = clean_data.drop('Price' , axis =1)

In [40]:
y = clean_data[['Price']]

In [41]:
x

brand  processor_brand  processor_name  processor_gnrtn  ram_gb  \
0        1                1               1                0       2   
1        5                1               1                0       2   
2        5                1               1                0       2   
3        1                1               2                0       3   
4        1                1               0                7       2   
..     ...              ...             ...              ...     ...   
818      1                0              10                7       2   
819      1                0              10                7       2   
820      1                0              10                7       2   
821      1                0              10                7       2   
822      5                0               8                0       3   

     ram_type  ssd  hdd  os  os_bit  graphic_card_gb  weight  warranty  \
0           1    0    1   2       1                0       0         3   
1           1    0    1   2       1                0       0         3   
2           1    0    1   2       1                0       0         3   
3           1    6    0   2       0                1       0         3   
4           1    0    3   2       1                0       0         3   
..        ...  ...  ...  ..     ...              ...     ...       ...   
818         1    1    0   2       1                0       0         0   
819         1    1    0   2       1                0       0         0   
820         1    1    0   2       1                2       0         0   
821         1    1    0   2       1                2       0         0   
822         1    6    0   0       1                0       2         3   

     Touchscreen  msoffice  rating  Number of Ratings  Number of Reviews  
0              0         0       1                  3                  0  
1              0         0       2                 65                  5  
2              0         0       2                  8                  1  
3              0         0       2                  0                  0  
4              0         0       2                  0                  0  
..           ...       ...     ...                ...                ...  
818            0         0       2                  0                  0  
819            0         0       2                  0                  0  
820            0         0       2                  0                  0  
821            0         0       2                  0                  0  
822            0         0       3                 18                  4  

[802 rows x 18 columns]

In [42]:
y

Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [43]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape  

((641, 18), (161, 18), (641, 1), (161, 1))

In [45]:
from sklearn.linear_model import LinearRegression

Lr = LinearRegression()
Lr.fit(x_train , y_train)

LinearRegression()

In [46]:
Lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'positive': False,
 'tol': 1e-06}

In [47]:
Lr.score(x_train, y_train) 

0.5836964629683771

In [48]:
pred = Lr.predict(x_test)

In [49]:
pred =pd.DataFrame(pred)

In [50]:
y_test

Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [51]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train, y_train)

c:\Users\bhatn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [52]:
pred =svr.predict(x_test)

In [53]:
x_test

brand  processor_brand  processor_name  processor_gnrtn  ram_gb  \
196      7                1               2                7       3   
299      1                1               2                1       3   
171      3                1               1                0       3   
537      4                1               3                0       0   
551      6                1               3                1       0   
..     ...              ...             ...              ...     ...   
368      1                1               2                1       3   
361      4                1               2                0       3   
446      3                1               2                1       3   
767      5                0               9                7       2   
529      5                1               3                1       0   

     ram_type  ssd  hdd  os  os_bit  graphic_card_gb  weight  warranty  \
196         2    0    3   2       0                2       0         3   
299         5    6    0   2       0                0       0         0   
171         1    4    1   2       1                0       2         0   
537         1    1    0   2       1                3       0         0   
551         1    1    0   2       1                4       0         1   
..        ...  ...  ...  ..     ...              ...     ...       ...   
368         5    6    0   2       1                0       0         0   
361         1    6    0   2       1                0       0         0   
446         1    4    1   2       1                0       0         0   
767         1    6    0   2       1                2       0         0   
529         1    6    0   2       0                0       0         3   

     Touchscreen  msoffice  rating  Number of Ratings  Number of Reviews  
196            0         0       3              10966               1185  
299            0         1       3                 76                 14  
171            0         1       4                  7                  5  
537            0         1       3                 17                  4  
551            0         0       3                 14                  3  
..           ...       ...     ...                ...                ...  
368            1         0       2                  0                  0  
361            1         0       4                  2                  1  
446            0         0       3                 47                  0  
767            0         0       2                  0                  0  
529            0         0       2                  0                  0  

[161 rows x 18 columns]

In [54]:
from sklearn.tree import DecisionTreeRegressor
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [55]:
dt.score(x_train, y_train) 

0.998034456706054

In [56]:
pred =dt.predict(x_test)

In [57]:
red =pd.DataFrame(pred)

In [58]:
y_test

Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [59]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [60]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(x_train , y_train)

KNeighborsRegressor()

In [61]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [62]:
knn.predict(x_test)

array([[ 47130. ],
       [ 63990. ],
       [ 63074. ],
       [ 69928. ],
       [ 75350. ],
       [131188. ],
       [ 47530. ],
       [ 70895.6],
       [ 72270. ],
       [ 90076.2],
       [ 46172. ],
       [ 72070. ],
       [ 71844.2],
       [118694. ],
       [ 53790. ],
       [ 88233.4],
       [ 74653.8],
       [ 64774. ],
       [ 64993.6],
       [136383. ],
       [ 56670. ],
       [ 53213.8],
       [ 79773.8],
       [ 65939.6],
       [ 35190. ],
       [ 54590. ],
       [ 60290. ],
       [172591.6],
       [ 72165.4],
       [ 63767.4],
       [ 54551.8],
       [ 72492. ],
       [ 52992.2],
       [ 89555.6],
       [ 67033.6],
       [ 54782. ],
       [121090. ],
       [ 64391.8],
       [ 58831.8],
       [ 67490. ],
       [ 56670. ],
       [ 69990. ],
       [ 53790. ],
       [ 39288. ],
       [ 79272. ],
       [ 67193.6],
       [ 63750. ],
       [ 66591.4],
       [ 59615.4],
       [119179.2],
       [128241. ],
       [105711.8],
       [ 692

In [63]:
x_train

brand  processor_brand  processor_name  processor_gnrtn  ram_gb  \
442      1                1               2                1       3   
598      1                1               3                0       0   
452      1                1               2                1       3   
696      3                0               8                7       3   
339      1                1               2                1       3   
..     ...              ...             ...              ...     ...   
73       5                1               1                0       2   
108      3                1               1                1       3   
275      5                1               2                0       3   
445      1                1               2                1       3   
104      1                1               1                1       3   

     ram_type  ssd  hdd  os  os_bit  graphic_card_gb  weight  warranty  \
442         1    4    1   2       0                0       0         0   
598         5    0    3   0       0                3       0         3   
452         1    4    1   2       1                1       0         0   
696         1    6    0   2       1                0       2         0   
339         5    6    0   2       1                0       0         0   
..        ...  ...  ...  ..     ...              ...     ...       ...   
73          1    4    0   2       0                0       0         3   
108         1    6    0   2       1                0       0         0   
275         1    6    0   2       1                1       0         0   
445         1    4    1   2       1                0       0         0   
104         1    6    0   2       1                0       0         0   

     Touchscreen  msoffice  rating  Number of Ratings  Number of Reviews  
442            0         1       3               1188                127  
598            0         0       2                  2                  1  
452            0         1       3                 33                  4  
696            0         1       2                  0                  0  
339            1         0       3                 35                  6  
..           ...       ...     ...                ...                ...  
73             0         0       2                  3                  0  
108            1         0       3                 10                  1  
275            0         1       2                  0                  0  
445            0         0       2                  0                  0  
104            0         1       3               2058                305  

[641 rows x 18 columns]

In [64]:
from sklearn.ensemble import RandomForestRegressor
# Using RandomForestRegressor for regression tasks

# Rfc = RandomForestClassifier()
Rfr=RandomForestRegressor()
Rfr.fit(x_train , y_train)
# Rfc.fit(x_train , y_train)

c:\Users\bhatn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [65]:
from sklearn.metrics import classification_report,precision_score,recall_score,confusion_matrix,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [66]:
df = DecisionTreeRegressor()
df.fit(x_train,y_train)

DecisionTreeRegressor()

In [67]:
df.score(x_test, y_test)


0.5150266521669131

In [68]:
pred = df.predict(x_test)