In [89]:
import pandas as pd

In [90]:
df = pd.read_csv(r"C:\Users\bhatn\Desktop\data science upflairs\Data-Science-AI-and-ML\Pandas\Credit (1).csv")

In [91]:
df.dropna(inplace=True)

In [92]:
df

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4501 rows x 9 columns]

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4501 entries, 0 to 4520
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        4501 non-null   float64
 1   job        4501 non-null   object 
 2   marital    4501 non-null   object 
 3   education  4501 non-null   object 
 4   balance    4501 non-null   int64  
 5   housing    4501 non-null   object 
 6   duration   4501 non-null   float64
 7   campaign   4501 non-null   int64  
 8   approval   4501 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 351.6+ KB


In [153]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4516    False
4517    False
4518    False
4519    False
4520    False
Length: 4500, dtype: bool

In [154]:
df.duplicated().sum()

np.int64(0)

In [155]:
df.drop_duplicates(inplace=True)

In [156]:
df.describe()

age       balance      duration
count  4500.000000   4500.000000  4.500000e+03
mean     41.391111   1423.561111  6.007646e+03
std      13.983651   3014.058886  3.578213e+05
min     -38.000000  -3313.000000 -7.990000e+02
25%      33.000000     68.750000  1.040000e+02
50%      39.000000    444.500000  1.850000e+02
75%      49.000000   1480.000000  3.290000e+02
max     416.000000  71188.000000  2.395650e+07

In [157]:
df

age     job status  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

     approval  
0          no  
1          no  
2          no  
3          no  
4          no  
...       ...  
4516       no  
4517       no  
4518       no  
4519       no  
4520       no  

[4500 rows x 8 columns]

In [158]:
df.head(10)

age     job status  marital  education  balance housing  duration approval
0  30.0     unemployed  married    primary     1787      no      79.0       no
1  33.0       services  married  secondary     4789     yes     220.0       no
2  35.0     management   single   tertiary     1350     yes     185.0       no
3  30.0     management  married   tertiary     1476     yes     199.0       no
4  59.0    blue-collar  married  secondary        0     yes     226.0       no
5  35.0     management   single   tertiary      747      no     141.0       no
6  36.0  self-employed  married   tertiary      307     yes     341.0       no
7  39.0     technician  married  secondary      147     yes     151.0       no
8  41.0   entrepreneur  married   tertiary      221     yes      57.0       no
9  43.0       services  married    primary      -88     yes     313.0       no

In [159]:
df.tail(10)

age     job status  marital  education  balance housing  duration  \
4511  46.0    blue-collar  married  secondary      668     yes    1263.0   
4512  40.0    blue-collar  married  secondary     1100     yes     660.0   
4513  49.0    blue-collar  married  secondary      322      no     356.0   
4514  38.0    blue-collar  married  secondary     1205     yes      45.0   
4515  32.0       services   single  secondary      473     yes     624.0   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

     approval  
4511      yes  
4512       no  
4513       no  
4514       no  
4515       no  
4516       no  
4517       no  
4518       no  
4519       no  
4520       no

In [161]:
df['job status']

0          unemployed
1            services
2          management
3          management
4         blue-collar
            ...      
4516         services
4517    self-employed
4518       technician
4519      blue-collar
4520     entrepreneur
Name: job status, Length: 4500, dtype: object

In [ ]:
df['job'].value_counts()

job
management       958
blue-collar      943
technician       765
admin.           477
services         415
retired          230
self-employed    182
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

In [ ]:
df['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

In [ ]:
df['job'].nunique()

12

In [ ]:
df[df['job'] == 'blue-collar']

age          job  marital  education  balance housing  duration  \
4     59.0  blue-collar  married  secondary        0     yes     226.0   
14    31.0  blue-collar  married  secondary      360     yes      89.0   
26    55.0  blue-collar  married    primary      627     yes     247.0   
37    32.0  blue-collar  married  secondary     2089     yes     132.0   
42    52.0  blue-collar  married  secondary     1117     yes     365.0   
...    ...          ...      ...        ...      ...     ...       ...   
4511  46.0  blue-collar  married  secondary      668     yes    1263.0   
4512  40.0  blue-collar  married  secondary     1100     yes     660.0   
4513  49.0  blue-collar  married  secondary      322      no     356.0   
4514  38.0  blue-collar  married  secondary     1205     yes      45.0   
4519  28.0  blue-collar  married  secondary     1137      no     129.0   

      campaign approval  
4            1       no  
14           1       no  
26           1       no  
37           1      yes  
42           1       no  
...        ...      ...  
4511         2      yes  
4512         2       no  
4513         2       no  
4514         4       no  
4519         4       no  

[943 rows x 9 columns]

In [ ]:
df.rename(columns={'job' : 'job status'}, inplace=True)

In [ ]:
df

age     job status  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4500 rows x 9 columns]

In [ ]:
df.drop(['campaign'] ,axis=1 ,inplace=True)

In [ ]:
df

age     job status  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

     approval  
0          no  
1          no  
2          no  
3          no  
4          no  
...       ...  
4516       no  
4517       no  
4518       no  
4519       no  
4520       no  

[4500 rows x 8 columns]

In [ ]:
char = df.select_dtypes(include='object')

In [ ]:
char 

job status  marital  education housing approval
0        unemployed  married    primary      no       no
1          services  married  secondary     yes       no
2        management   single   tertiary     yes       no
3        management  married   tertiary     yes       no
4       blue-collar  married  secondary     yes       no
...             ...      ...        ...     ...      ...
4516       services  married  secondary     yes       no
4517  self-employed  married   tertiary     yes       no
4518     technician  married  secondary      no       no
4519    blue-collar  married  secondary      no       no
4520   entrepreneur   single   tertiary     yes       no

[4500 rows x 5 columns]

In [162]:
num = df.select_dtypes(exclude='object')

In [163]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [164]:
char['marital'].unique()

array([0, 1, 2])

In [324]:
job_status_dic={
    'married':0,
    'single' :1,
    'divorced' :2
    }

In [203]:
char['marital'] = char['marital'].map(job_status_dic)

In [204]:
char['marital'].unique()

array([nan])

In [205]:
char['education'].unique()

array([nan])

In [206]:
education_dict ={
    'primary' : 0,
    'secondary' :1,
    'tertiary': 2,
    'unknown':3
}

In [207]:
char['education'] = char['education'].map(education_dict)

In [208]:
char['education'].unique()

array([nan])

In [325]:
char

job status  marital  education housing approval
0             10      NaN        NaN      no       no
1              7      NaN        NaN     yes       no
2              4      NaN        NaN     yes       no
3              4      NaN        NaN     yes       no
4              1      NaN        NaN     yes       no
...          ...      ...        ...     ...      ...
4516           7      NaN        NaN     yes       no
4517           6      NaN        NaN     yes       no
4518           9      NaN        NaN      no       no
4519           1      NaN        NaN      no       no
4520           2      NaN        NaN     yes       no

[4500 rows x 5 columns]

In [326]:
from sklearn.preprocessing import LabelEncoder   ## label encoder is use for whn classes are more then how to assign it ...  ##onedotcoder == for assign 01=,1
Le =LabelEncoder()
char['job status']=Le.fit_transform(char['job status'])


In [241]:
char['job status'].unique()

array([10,  7,  4,  1,  6,  9,  2,  0,  8,  3,  5, 11])

In [242]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [243]:
char

job status  marital  education housing approval
0             10      NaN        NaN      no       no
1              7      NaN        NaN     yes       no
2              4      NaN        NaN     yes       no
3              4      NaN        NaN     yes       no
4              1      NaN        NaN     yes       no
...          ...      ...        ...     ...      ...
4516           7      NaN        NaN     yes       no
4517           6      NaN        NaN     yes       no
4518           9      NaN        NaN      no       no
4519           1      NaN        NaN      no       no
4520           2      NaN        NaN     yes       no

[4500 rows x 5 columns]

In [271]:
clean_data = pd.concat([char,num], axis=1)

In [272]:
app_dict ={'no':0, 'yes':1}

In [273]:
clean_data['housing']= clean_data['housing'].map(app_dict)

In [274]:
clean_data

job status  marital  education  housing approval   age  balance  \
0             10      NaN        NaN        0       no  30.0     1787   
1              7      NaN        NaN        1       no  33.0     4789   
2              4      NaN        NaN        1       no  35.0     1350   
3              4      NaN        NaN        1       no  30.0     1476   
4              1      NaN        NaN        1       no  59.0        0   
...          ...      ...        ...      ...      ...   ...      ...   
4516           7      NaN        NaN        1       no  99.0     -333   
4517           6      NaN        NaN        1       no  57.0    -3313   
4518           9      NaN        NaN        0       no  57.0      295   
4519           1      NaN        NaN        0       no  28.0     1137   
4520           2      NaN        NaN        1       no  44.0     1136   

      duration  
0         79.0  
1        220.0  
2        185.0  
3        199.0  
4        226.0  
...        ...  
4516     329.0  
4517    -153.0  
4518     151.0  
4519     129.0  
4520     345.0  

[4500 rows x 8 columns]

In [298]:
clean_data.to_csv('new_cleaned_credit.csv')

In [322]:
df.dropna(inplace=True)

In [323]:
clean_data

job status  marital  education  housing approval   age  balance  \
0             10      NaN        NaN        0       no  30.0     1787   
1              7      NaN        NaN        1       no  33.0     4789   
2              4      NaN        NaN        1       no  35.0     1350   
3              4      NaN        NaN        1       no  30.0     1476   
4              1      NaN        NaN        1       no  59.0        0   
...          ...      ...        ...      ...      ...   ...      ...   
4516           7      NaN        NaN        1       no  99.0     -333   
4517           6      NaN        NaN        1       no  57.0    -3313   
4518           9      NaN        NaN        0       no  57.0      295   
4519           1      NaN        NaN        0       no  28.0     1137   
4520           2      NaN        NaN        1       no  44.0     1136   

      duration  
0         79.0  
1        220.0  
2        185.0  
3        199.0  
4        226.0  
...        ...  
4516     329.0  
4517    -153.0  
4518     151.0  
4519     129.0  
4520     345.0  

[4500 rows x 8 columns]

In [300]:
df1 = pd.read_csv('new_cleaned_Credit.csv')

In [301]:
df1

Unnamed: 0  job status  marital  education  housing approval   age  \
0              0          10      NaN        NaN        0       no  30.0   
1              1           7      NaN        NaN        1       no  33.0   
2              2           4      NaN        NaN        1       no  35.0   
3              3           4      NaN        NaN        1       no  30.0   
4              4           1      NaN        NaN        1       no  59.0   
...          ...         ...      ...        ...      ...      ...   ...   
4495        4516           7      NaN        NaN        1       no  99.0   
4496        4517           6      NaN        NaN        1       no  57.0   
4497        4518           9      NaN        NaN        0       no  57.0   
4498        4519           1      NaN        NaN        0       no  28.0   
4499        4520           2      NaN        NaN        1       no  44.0   

      balance  duration  
0        1787      79.0  
1        4789     220.0  
2        1350     185.0  
3        1476     199.0  
4           0     226.0  
...       ...       ...  
4495     -333     329.0  
4496    -3313    -153.0  
4497      295     151.0  
4498     1137     129.0  
4499     1136     345.0  

[4500 rows x 9 columns]

In [302]:
df1.dropna(inplace=True)

In [303]:
# x =df1.drop('U', axis =1) 

In [304]:
# y =df1[['age']]

In [305]:
df1.drop('Unnamed: 0', axis =1,inplace=True) 


In [306]:
df1

Empty DataFrame
Columns: [job status, marital, education, housing, approval, age, balance, duration]
Index: []

In [307]:
x = clean_data.drop('approval' , axis =1)

In [308]:
y = clean_data[['approval']]

In [309]:
x

job status  marital  education  housing   age  balance  duration
0             10      NaN        NaN        0  30.0     1787      79.0
1              7      NaN        NaN        1  33.0     4789     220.0
2              4      NaN        NaN        1  35.0     1350     185.0
3              4      NaN        NaN        1  30.0     1476     199.0
4              1      NaN        NaN        1  59.0        0     226.0
...          ...      ...        ...      ...   ...      ...       ...
4516           7      NaN        NaN        1  99.0     -333     329.0
4517           6      NaN        NaN        1  57.0    -3313    -153.0
4518           9      NaN        NaN        0  57.0      295     151.0
4519           1      NaN        NaN        0  28.0     1137     129.0
4520           2      NaN        NaN        1  44.0     1136     345.0

[4500 rows x 7 columns]

In [310]:
y

approval
0          no
1          no
2          no
3          no
4          no
...       ...
4516       no
4517       no
4518       no
4519       no
4520       no

[4500 rows x 1 columns]

In [311]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [312]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape  

((3600, 7), (900, 7), (3600, 1), (900, 1))

In [313]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

In [314]:
y_train['approval'].nunique()

2

In [315]:
app_dict = {'no':0, 'yes':1}

In [316]:
y_train['approval']= y_train['approval'].map(app_dict)

In [317]:
y_train['approval'].unique()

array([0, 1])

In [318]:
x_train['housing']= x_train['housing'].map(app_dict)

In [319]:
char  

job status  marital  education housing approval
0             10      NaN        NaN      no       no
1              7      NaN        NaN     yes       no
2              4      NaN        NaN     yes       no
3              4      NaN        NaN     yes       no
4              1      NaN        NaN     yes       no
...          ...      ...        ...     ...      ...
4516           7      NaN        NaN     yes       no
4517           6      NaN        NaN     yes       no
4518           9      NaN        NaN      no       no
4519           1      NaN        NaN      no       no
4520           2      NaN        NaN     yes       no

[4500 rows x 5 columns]

In [320]:
from sklearn.linear_model import LinearRegression

Lr = LinearRegression()
Lr.fit(x_train , y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
Lr.score(x_train, y_train) 

0.01621723827922139

In [ ]:
# x_test['housing']= x_train['housing'].map(app_dict)

In [ ]:
pred =Lr.predict(x_test)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
pred =pd.DataFrame(pred)


In [ ]:
y_test

approval
2331         1
3701         0
2987         1
3005         1
473          1
...        ...
916          0
814          0
2952         1
3725         0
3271         0

[900 rows x 1 columns]

In [ ]:
x_test

job status  marital  education  housing    age  balance  duration
2331           4        0          2        1   30.0      102     470.0
3701           1        0          1        1   48.0     1738     349.0
2987           2        1          1        0  338.0     2543     223.0
3005           6        0          3        0   51.0     2094     458.0
473            0        0          1        0   61.0     4608     212.0
...          ...      ...        ...      ...    ...      ...       ...
916            1        0          1        0   36.0       13     284.0
814            9        0          1        1   47.0      -75      57.0
2952           8        1          2        0   22.0      691     338.0
3725           9        0          3        1   45.0      473     147.0
3271           7        1          1        1   44.0     5045      20.0

[900 rows x 7 columns]

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train , y_train)

NameError: name 'x_train' is not defined

In [ ]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train , y_train)

ValueError: could not convert string to float: 'no'

In [ ]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
knn.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

Rfc = RandomForestClassifier()
Rfc.fit(x_train , y_train)

RandomForestClassifier()