In [2]:
import numpy as np   ##allias shortform  -as

In [3]:
np.array([45])

array([45])

In [4]:
np.__version__

'2.3.1'

In [5]:
# list , array
lst = [1,2,3,4,5,6,7,6,7]
arr =np.array(lst)


In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 6, 7])

In [7]:
arr =np.array([2,4,6,7,8])

In [8]:
arr

array([2, 4, 6, 7, 8])

In [9]:
lst = [1,2,3,4,5,6,7,6,7]
print("type of list" ,type(lst))
arr =np.array(lst)
print(arr)
print("typr4s of array" ,type(arr))

type of list <class 'list'>
[1 2 3 4 5 6 7 6 7]
typr4s of array <class 'numpy.ndarray'>


In [10]:
  arr =np.array(list(range(1,21)))
  arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((5,10))   ##5-row 10-column

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
##1d array convert into 2d array     ---2[[ 2 brack is 2d array]]
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
arr.reshape((10,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr = np.random.randint(1,5,9)
arr

array([3, 4, 2, 3, 1, 3, 2, 2, 4], dtype=int32)

In [ ]:
arr = np.random.randint(1,5,(3,3))
arr

array([[2, 2, 1],
       [2, 2, 4],
       [1, 1, 3]], dtype=int32)

In [ ]:
arr = np.random.random(10)
arr

array([0.31996367, 0.88110816, 0.92773911, 0.94754943, 0.72059781,
       0.15472363, 0.9047415 , 0.29872971, 0.99895762, 0.15391529])

In [39]:
arr = np.random.random((5,10))
arr

array([[0.13603831, 0.46069357, 0.68089558, 0.31701419, 0.59781108,
        0.25657886, 0.90786215, 0.17167269, 0.55422418, 0.03300056],
       [0.29591981, 0.3442561 , 0.58074003, 0.26383729, 0.61311471,
        0.89644711, 0.81553091, 0.20196449, 0.90102796, 0.1217294 ],
       [0.33938564, 0.2594524 , 0.83829688, 0.99289625, 0.15558061,
        0.85873444, 0.94954664, 0.14920455, 0.66806037, 0.7469201 ],
       [0.89873719, 0.16053952, 0.79168483, 0.65068152, 0.25354915,
        0.37371433, 0.85583287, 0.30574822, 0.92017179, 0.56568203],
       [0.39607159, 0.88230231, 0.77463972, 0.25202529, 0.53770289,
        0.6803597 , 0.25689234, 0.29963888, 0.76580395, 0.64519709]])

In [41]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [42]:
print("shape if array" ,arr.shape)
print("size of array",arr.size)
print("data types",arr.dtype)
print("size of no.dimen",arr.ndim)



arr.ndim

shape if array (12, 5)
size of array 60
data types int64
size of no.dimen 2


2

In [43]:
##3covert 2d array into 1

arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [45]:
##task --differnce b/w raven and flatten



In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [47]:
arr.shape

(12, 5)

In [48]:
##transpose

arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [49]:
arr.T.shape

(5, 12)

In [52]:
arr = np.arange(30)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
arr[20]

np.int64(20)

In [54]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [97]:
##replace

arr[0] = 100

In [98]:
arr

array([100,   2,   3,   5,   6,   9])

In [99]:
arr = np.arange(60).reshape(12,5)

In [100]:
arr[1,3:5]

array([8, 9])

In [101]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [102]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [103]:
arr[1,1]=100

In [104]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [105]:
arr[11,4]  ##to fetch last varianle

np.int64(59)

In [106]:
arr[-1]

array([55, 56, 57, 58, 59])

In [107]:
arr[-1][-1]

np.int64(59)

In [108]:
arr[11][-1]

np.int64(59)

In [109]:
arr[-1,-1]

np.int64(59)

In [110]:
arr = np.array(np.arange(225).reshape(5,15,3))

In [111]:
arr.ndim , arr.shape , arr.size ,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [112]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [113]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [114]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [115]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [116]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [117]:
arr[0,0:1,0:1]

array([[0]])

In [118]:
arr[0,1,1] =1000  ##replacingg

In [119]:
arr[0,1,1] 

np.int64(1000)

In [120]:
arr =np.array([1,5,6,9,2,3,])

In [121]:
arr.sort()

In [122]:
arr

array([1, 2, 3, 5, 6, 9])

In [123]:
arr+2

array([ 3,  4,  5,  7,  8, 11])

In [124]:
arr-2

array([-1,  0,  1,  3,  4,  7])

In [125]:
arr*2

array([ 2,  4,  6, 10, 12, 18])

In [126]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([1,2,3,5])

In [127]:
arr1 + arr2
arr1 - arr2
arr1 * arr2


array([ 1,  4,  9, 25])

## Ravel() and Flatten()

| Aspect                         | `ravel()`                                                                    | `flatten()`                                                          |
| ------------------------------ | ---------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| **Definition**                 | Converts a multi-dimensional array into a 1D array **as a view if possible** | Converts a multi-dimensional array into a 1D array **as a new copy** |
| **Return Type**                | Returns a **view** of the original array (if possible), else a copy          | Always returns a **new copy** of the original array                  |
| **Effect on Original Array**   | If view is returned, **changes in new array affect the original array**      | Changes in the new array **do not affect the original array**        |
| **Memory Usage**               | More memory-efficient (no copy unless needed)                                | Uses more memory (always copies the data)                            |
| **Speed / Performance**        | Faster (especially for large arrays)                                         | Slightly slower due to copying                                       |
| **Mutability**                 | Modifying `ravel()` result **may** change the original array                 | Modifying `flatten()` result **won’t** change the original array     |
| **Use Case**                   | When you want a quick 1D view and don’t need a separate copy                 | When you need a completely separate 1D copy for further processing   |
| **Function Type**              | Method of NumPy arrays: `array.ravel()`                                      | Method of NumPy arrays: `array.flatten()`                            |
| **Required Memory Allocation** | May **reuse** existing memory if it returns a view                           | **Allocates new memory** every time                                  |
| **Flexibility**                | Flexible: adapts based on array’s memory layout                              | Always consistent: new data no matter what                           |
| **Real-life Analogy**          | Like **rearranging the same original pages** into a row                      | Like **photocopying the pages** and laying out the copy in a row     |
| **Flattening Order**           | Default: row-major (`C` order), but can specify (`C`, `F`, etc.)             | Same: default is `C` order, order can also be specified              |
| **Function Available In**      | NumPy only                                                                   | NumPy only                                                           |


In [128]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("Original array:\n", a)

# Using ravel()
r = a.ravel()
r[0] = 100  # Modify the first element in ravel result
print("\nAfter modifying ravel result:")
print("Ravel result:", r)
print("Original array after ravel:", a)

# Using flatten()
f = a.flatten()
f[0] = 200  # Modify the first element in flatten result
print("\nAfter modifying flatten result:")
print("Flatten result:", f)
print("Original array after flatten:", a)


Original array:
 [[1 2]
 [3 4]]

After modifying ravel result:
Ravel result: [100   2   3   4]
Original array after ravel: [[100   2]
 [  3   4]]

After modifying flatten result:
Flatten result: [200   2   3   4]
Original array after flatten: [[100   2]
 [  3   4]]
